### ISSUE TITLE
How to check checkbox

### ISSUE THREAD

**Issue by nkchouhan** [jkraemer/pdf-forms#22]
I have look deep into the gem but  Could not found any method that check the checkbox.
So could you please let me know how can I check the checkbox.

**Comment by sguha00** [comment]
I'm having trouble with this. The dump_data_fields output for a field is
    ---
FieldType: Button
FieldName: form1[0].#subform[0].Line3b_Unit[0]
FieldNameAlt: Check this box if the address is a suite.  
FieldFlags: 0
FieldValue: Off
FieldJustification: Left
FieldStateOption:  STE 
FieldStateOption: Off

but setting `form1[0].#subform[0].Line3b_Unit[0]` to `STE` has no effect

**Comment by jkraemer** [comment]
Hi,
don't know what the problem might be, but can you try to check the box using a pdf viewer, save a copy and run dump_data_fields on that copy?

**Comment by sguha00** [comment]
When I check the `STE` box, I get the following:

---
FieldType: Button
FieldName: form1[0].#subform[0].Line3b_Unit[0]
FieldFlags: 0
FieldValue:  STE 
FieldJustification: Left
FieldStateOption:  STE 
FieldStateOption: Off

**Comment by jkraemer** [comment]
I think there is a Space character in front of that 'STE'. If you carefully look at your output with a fixed width font you should notice that in both the FieldStateOption as well as the FieldValue there are two spaces after the `:`. So you will need to set the field to ` STE` with a space prepended and it should work. This error happens sometimes because Acrobat form editor does not strip the values when creating the form.

**Comment by sguha00** [comment]
I see that the value is being stripped in the `quote` function https://github.com/jkraemer/pdf-forms/blob/ce5b17d4d8cbeb781352bade353e93425e20d3aa/lib/pdf_forms/fdf.rb#L52 so ` STE` isn't working either. I ended up editing the form and removing the extra whitespace around that option and getting it to work, but I'm wondering if the value should be stripped.

Thanks for the help!

**Comment by fro** [comment]
@jkraemer A huge thank to you pdftk dump_data_fields was a AhAh! moment for me. ;-)

**Comment by jkraemer** [comment]
@sguha00 you are right about the stripping. I've removed it now.

**Comment by matisoffn** [comment]
We are having a similar problem.  When calling `get_field_names` our radio fields & checkbox fields aren't even coming in.

When we run `dump_data_fields` in the terminal, it includes the field.

What could be wrong?

**Comment by nickooolas** [comment]
For anyone wondering why fields don't display sometimes - I've noticed that sometimes if you open the PDF in Mac, or just depending on how you setup the PDF it doesn't recognise the fields. 

I've noticed if you copy the form fields (when in form editing mode in Acrobat), literally copy the existing one, delete copied one, then leave new one in place, it does **something**, and then they are recognised by PDFTK, and hence `pdf-forms`

(I'm assuming you're using Acrobat to embed/modify the fields names, properties)

**Comment by AngelAlvarado** [comment]
For what is worth, nowadays you can edit these values with Acrobat Pro DC
![image](https://user-images.githubusercontent.com/780515/57100543-0b4d6980-6cd4-11e9-8ebf-7c24cfcdf649.png)

**Comment by caballeroe359** [comment]
> We are having a similar problem. When calling `get_field_names` our radio fields & checkbox fields aren't even coming in.
> 
> When we run `dump_data_fields` in the terminal, it includes the field.
> 
> What could be wrong?

Were you able to figure this out? I'm currently facing the same issue. I've tried adding the extra spaces as mentioned above, when I check my logs I can see the extra spaces in the command yet the issue persists. Two days, it's driving me crazy

**Comment by caballeroe359** [comment]
> > We are having a similar problem. When calling `get_field_names` our radio fields & checkbox fields aren't even coming in.
> > When we run `dump_data_fields` in the terminal, it includes the field.
> > What could be wrong?
> 
> Were you able to figure this out? I'm currently facing the same issue. I've tried adding the extra spaces as mentioned above, when I check my logs I can see the extra spaces in the command yet the issue persists. Two days, it's driving me crazy

I believe I've found the issue. I was experiencing the same problem as OP. I believe we are even using the same forms. 
I've solved the issue by expanding the checkbox/button field. The form had the buttons very tiny, which worked if you edited it using adobe or so but not using fdf. I expanded the checkboxes and it worked like a charm.

**Comment by balbesina** [comment]
I'm wondering if there is a way to get a group of radios together or have some common indicator for them e.g. field "group". Because radios are basically one field with many values. What i see in the pdftk output is:

```
--- FieldType: Button FieldName: field_a1 FieldFlags: 0 FieldValue: Off FieldJustification: Left FieldStateOption: Off FieldStateOption: Yes 
--- FieldType: Button FieldName: field_a2 FieldFlags: 0 FieldValue: Off FieldJustification: Left FieldStateOption: Off FieldStateOption: Yes 
```

what i expect to see instead is
```
--- FieldType: Button FieldName: field_a FieldFlags: 0 FieldValue: Off FieldJustification: Left FieldStateOption: a1 FieldStateOption: a2
```

or at least have some group attribute
```
--- FieldType: Button FieldName: field_a1 FieldFlags: 0 FieldValue: Off FieldJustification: Left FieldStateOption: Off FieldStateOption: Yes Group: a
--- FieldType: Button FieldName: field_a2 FieldFlags: 0 FieldValue: Off FieldJustification: Left FieldStateOption: Off FieldStateOption: Yes Group: a
```
