### ISSUE TITLE
insert image into one of fields

### ISSUE THREAD

**Issue by ckgagan** [jkraemer/pdf-forms#24]
Is it possible to insert image into the fields. I don't see it mentioned in Readme file.
If yes how do I accomplish it?
Thanks

**Comment by jkraemer** [comment]
I never heard of the possibility to insert images into pdf forms. Can you point me to any piece of documentation about this?

Sent from my phone.

-----Original Message-----

**Comment by ahey** [comment]
This should be possible in [pdftk via multistamp](https://www.pdflabs.com/docs/how-to-add-headers-footers-watermarks-and-stamps-to-pdf/)

**Comment by jkraemer** [comment]
The question was how to insert an image into form fields, if I understand correctly multistamp isn't related to PDF forms, it just overlays PDF documents.

**Comment by vsrboth** [comment]
@jkraemer 
allow me to give an example like inserting digital signature to the pdf, I am right now looking for this kind of thing, so that I can insert `digital signature` to my pdf file.

**Comment by jkraemer** [comment]
I don't get what digital signatures have to do with images.
If you want to put an image of an actual signature somebody put on paper with a pen into a PDF, then you can possibly do so with `pdftk multistamp` (see link above). See `test/pdftk_wrapper_test.rb` for an example of how to call this command through pdf-forms.

**Comment by yul** [comment]
there are fields with pdf type 'Signature', they are supposed to capture signature written on the screen. 
For example this is part of dump_fields output:

`FieldType: Signature
FieldName: Signature1
FieldFlags: 0
FieldJustification: Left`

Is there a way to fill such fields with pdftk? I could probably convert signature to png and insert it as an image, but I was looking for more native (easy?) way.

**Comment by corroded** [comment]
What about application forms where you need to put your photo or something? Does that count as putting an image into a form? 

I'll take a look at `test/pdftk_wrapper_test.rb` and see if that helps me out on that regard.
