### ISSUE TITLE
RedHat 7 binary like pdftk known?

### ISSUE THREAD

**Issue by andywenk** [jkraemer/pdf-forms#26]
Hi,

first of all thanks a lot for this gem. It's really cool and works super reliable ;-).

Well, we now have the problem, that pdftk is not available under RedHat 7. It is also not possible to compile it there (missing dependencies). Is it possible to use an other binary? Any experience with this? 

There is for example https://github.com/documentcloud/pdftailor or http://qpdf.sourceforge.net 

Any info is highly appreciated ;-)

Cheers

Andy

**Comment by jkraemer** [comment]
If any of these alternative binaries also has the capability to take data from an (x)fdf file and put it into a PDF form then it should be possible to replace pdftk with it. However I have no experience with the tools you mentioned, so I cannot be of much help here.

**Comment by andywenk** [comment]
Hi Jens,

sorry for late reply and thanks a lot for the info ;-). Actually we have downgraded to RHEL 6 because there is a working binary available. RHEL 7 brings also a lot of other head scratching issues btw.

Cheers

Andy
