### ISSUE TITLE
`fill_form` not working

### ISSUE THREAD

**Issue by milesmatthias** [jkraemer/pdf-forms#29]
I'm trying to programmatically fill out this PDF: http://www.irs.gov/pub/irs-pdf/f1065sk1.pdf

and I'm seeing if your gem can help me. Here's the test script I'm using:

```ruby
#!/usr/bin/env ruby

require 'pdf_forms'
require 'pry'

pdftk = PdfForms::PdftkWrapper.new('/usr/local/bin/pdftk')
pdf   = PdfForms::Pdf.new('2014_k1.pdf', pdftk)

field_names = pdf.fields.map(&:name)

field_values = field_names.map do |name|
  ret = {}
  ret[ name ] = name
  ret
end

pdftk.fill_form '2014_k1.pdf', 'filledout_k1.pdf', field_values
```

A PDF named `filledout_k1.pdf` is written to disk, but it doesn't have any fields filled out.

Do I need to convert the PDF to some other format to be able to fill it? I haven't done much with PDFs so I'm not sure how to go about it.

**Comment by jkraemer** [comment]
In your code `field_values` is an array of one-element hashes, but `fill_form` takes a single hash holding the data to fill in.

I think this
~~~~ruby
field_values = Hash[ pdf.fields.map{|f| [f.name, f.name]} ]
~~~~

does what you want.

**Comment by milesmatthias** [comment]
That worked, thanks for pointing out my oversight @jkraemer and nice work on this gem!
