### ISSUE TITLE
Adding dynamic data to PDF

### ISSUE THREAD

**Issue by kavitakanojiya** [jkraemer/pdf-forms#33]
Hey @jkraemer ,

I have a very simple requirement that I am suppose to create PDF from dynamic/runtime-generated data into a PDF. Is this possible with this library ?
It seems we need to mention the necessary variables before filling up the pdf.

Any help on this will help alot

Thanks.

**Comment by jkraemer** [comment]
Hi,
the fields a PDF form has is determined when the form is created (i.e. with Adobe Acrobat). This library is for filling out a given PDF form by assigning values to these fields. So the values are dynamic, but the fields a form has are pre-determined. For more flexibility you might consider writing the whole PDF from scratch i.e. with the (very nice, btw) prawn ruby library.
