### ISSUE TITLE
SafeShell breaks JRUBY

### ISSUE THREAD

**Issue by Ch4s3** [jkraemer/pdf-forms#34]
Version 1.02 of safeshell calls `fork`, causing [this](https://github.com/envato/safe_shell/issues/3) issue. Can you look into a temporary fix until they have 1.03, or otherwise be on the lookout for them to do that?

**Comment by jkraemer** [comment]
non-forking safeshell 1.0.3 is out and I changed the dependency accordingly. which broke support for Ruby 1.9, which made me tag the new version of pdf-forms as 1.0. I think trading new JRuby vs (very) old MRI is a good deal :)

**Comment by Ch4s3** [comment]
Cool, thanks! I was following along, I happened to catch it in production right after someone posted the issue on safeshell! I'm really happy this got resolved so quickly.
