### ISSUE TITLE
Pdf form

### ISSUE THREAD

**Issue by AmmadJavaid** [jkraemer/pdf-forms#36]
I have issue in the getting the field names from my pdf form. I did the following

    pdftk = PdfForms.new('/usr/local/bin/pdftk')
    pdftk.get_field_names("/home/my_user/my_form.pdf")

its return [].I have that form
[my_form.pdf](https://github.com/jkraemer/pdf-forms/files/32796/my_form.pdf)

**Comment by rahilsondhi** [comment]
I didn't look at your form, but if you use Adobe Acrobat to create a text field, that text field should be returned in `get_field_names`.

**Comment by jkraemer** [comment]
that pdf doesn't have any fields.
