### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tochman** [jkraemer/pdf-forms#40]
Hi, Perhaps a newbie question but I need some help.

I'm on OSX and I installed PDFtk Server from [here](https://www.pdflabs.com/tools/pdftk-server/) and, of course, the `pdf-forms` gem  itself. 

I jump in to irb to do some manual tests of the functionality and the first thing I encounter is a permissions error. 
```
2.2.1 :001 > require 'pdf_forms'
 => true 
2.2.1 :002 > pdftk = PdfForms.new('/opt/pdflabs/pdftk/')
Errno::EACCES: Permission denied - /opt/pdflabs/pdftk/
	from /Users/thomas/.rvm/gems/ruby-2.2.1/gems/safe_shell-1.0.3/lib/safe_shell.rb:10:in `spawn'
	from /Users/thomas/.rvm/gems/ruby-2.2.1/gems/safe_shell-1.0.3/lib/safe_shell.rb:10:in `execute'
        ....
```
Any ideas?

**Comment by tochman** [comment]
Next time I'll read the instructions better... Sorry about this.

**Comment by nige-s** [comment]
what was the issue?

**Comment by dgbtech** [comment]
stucked here....what was it???

**Comment by jkraemer** [comment]
This particular permission denied error was caused by the given path not pointing to the pdftk executable but a directory.

**Comment by dgbtech** [comment]
I installed pdftk in ubuntu 16 via soft manager and there wasnt any executable, got it installing via apt-get. Path Works fine now. thaks!
