### ISSUE TITLE
Some checkboxes are larger in the output than they were in the input

### ISSUE THREAD

**Issue by losmurfs** [jkraemer/pdf-forms#43]
I used pdftk to fill in a form but some (most) of the checkboxes are much larger in the output than they were in the original PDF.
![before](https://cloud.githubusercontent.com/assets/10159345/13336268/63a6bb18-dbd2-11e5-97f3-a48d803c713d.png)
![after](https://cloud.githubusercontent.com/assets/10159345/13336274/673c2f60-dbd2-11e5-9c0c-943691a3302d.png)

**Comment by jkraemer** [comment]
This is nothing this library (or even PDFTK) can do anything about. The cause most probably is the source PDF form - check settings like fonts and font sizes on the form.
