### ISSUE TITLE
PDF Security not working

### ISSUE THREAD

**Issue by eiapopeia** [jkraemer/pdf-forms#44]
Hi @jkraemer 

Been a long time. Nice to "see" you again :)

I have a problem regarding the security options in PDF-Forms.

When using the options `encrypt_password` or `encrypt_password` they are not used. This is because of the Line 43 of current `PdftkWrapper`:

`append_options args, fill_options`

The `append_options` function in fact returns the new args but they are not used. Changing it to 

`args = append_options args, fill_options`

brings up another error. In `PdftkWrapperTest#test_fill_form_encrypted_and_flattened_with_encrypt_options` it says:

> PdfForms::PdftkError: failed to fill form with command
> /usr/bin/pdftk test/fixtures/form.pdf fill_form /tmp/pdf_forms-fdf20160301-3337-dzbs59 output output.pdf flatten encrypt_128bit owner_pw /tmp/pdf_forms-fdf20160301-3337-dzbs59 allow printing
> command output was:
> Error: Unexpected data in output section: 
>       allow printing
> Exiting.
> Errors encountered.  No output created.
> Done.  Input errors, so no output created.
> 
> failing form data has been saved to /tmp/20160301152611.fdf

Executing the same command in a shell works. Also when not using SafeShell gem but unsafe `%x(#{pdftk} #{args.flatten.join(' ')})` it works. 

Do you have any idea?

Fun fact: The owner password is autmagically set super safe :)

**Comment by jkraemer** [comment]
Hi!

Handling of `args` is fixed. 'allow printing' was handled as a single argument which is not what pdftk expects - when using `%x` it goes through the shell and there it's naturally two arguments. I fixed that as well.

And we're using SecureRandom now for the default password ;)

Mit besten Grüßen aus Quezon City :)

**Comment by eiapopeia** [comment]
Works like a charm!

Thanks a lot for the quick help.
