### ISSUE TITLE
Document supported distributions

### ISSUE THREAD

**Issue by fulldecent** [jkraemer/pdf-forms#46]
Please document supported OS distributions this project is targeting.

Enterprise users may be interested to know that the latest version of CentOS (version 7) does *not* support `pdftk`, a dependency of this project.

**Comment by jkraemer** [comment]
The `README` clearly states that `pdftk` is required and also provides a link to it's website.

I won't start maintaining a list of operating systems where `pdftk` works / does not work. For RedHat / CentOS this information is [already present](https://www.pdflabs.com/docs/install-pdftk-on-redhat-or-centos/), along with instructions about how to build from source (did you try that?).
