### ISSUE TITLE
Hyphen being replaced with question mark in PDF

### ISSUE THREAD

**Issue by EricBoersma** [jkraemer/pdf-forms#50]
I have a line on a PDF form which is being filled with the following text or text of a similar format: `Lansing, MI 48901‑0726`. In the PDF form itself, the line reads `Lansing, MI 48901?0726`. I've confirmed that the text doesn't have a question mark prior to being sent to `fill_form`, but after that I'm not sure what's happening to translate the hyphen to a question mark.

**Comment by jkraemer** [comment]
Most often such problems stem from missing characters in the font being used in the pdf. 
What does `pdftk file.pdf dump_data_utf8` output when you run it on the filled out form that shows the question mark? If the `-` is there in the field value it's not a problem with pdftk or this gem, but a problem with your PDF. Check the fonts used, check if it's really a simple `-` or some other unicode char that just looks like `-` and which maybe isn't part of the font that is used in the PDF.

**Comment by jkraemer** [comment]
If you want me to investigate this further please reopen and supply the pdf where I can reproduce the problem.
