### ISSUE TITLE
The result of a check field should be a boolean

### ISSUE THREAD

**Issue by edusantana** [jkraemer/pdf-forms#52]
Instead of returning 'Off', it should return `false`.

**Comment by jkraemer** [comment]
pull requests welcome, I promise to be more responsive than the last time ;)

**Comment by edusantana** [comment]
Thanks! Can I suggest the use of a [change log ou release notes?](https://github.com/skywinder/github-changelog-generator)

**Comment by jkraemer** [comment]
there's a History.txt in the project root which I try to keep updated whenever I release a new version, is that what you're looking for?

**Comment by jkraemer** [comment]
closing this, it's been 2 years
