### ISSUE TITLE
UTF-8 chars are not displayed in the filled PDF

### ISSUE THREAD

**Issue by oki** [jkraemer/pdf-forms#53]
Hi,

I have test pdf: http://s000.tinyupload.com/?file_id=77431117353383489288

I am filling in data with small script:

```ruby
require "pp"

template_file = File.join(Rails.root, "form_example.pdf")
output_file = "output.pdf"

pdftk = PdfForms.new(`which pdftk`.chomp, utf8_fields: false, data_format: "XFdf")

pp pdftk.get_field_names template_file

pdf_data = {
  "name" => "różowy słoń ma usiąść na tępych gwoździach"
}

pdftk.fill_form template_file, output_file, pdf_data
```
After run got: http://take.ms/DrupC all utf8 letters dissapear (except ó)
Also attached generated pdf file: http://s000.tinyupload.com/index.php?file_id=32840734551043583650

Any idea what the problem is here? Why UTF-8 chars are not displayed?
Thanks for any help or experience.

**Comment by jkraemer** [comment]
Running `pdftk output.pdf dump_data_fields_utf8` yields the following result:

~~~
---
FieldType: Text
FieldName: name
FieldFlags: 0
FieldValue: różowy słoń ma usiąść na tępych gwoździach
FieldJustification: Left
~~~

I'd say the data is stored properly but your PDF lacks the proper font to display them.

**Comment by phoet** [comment]
this should be a disclaimer in the readme 😄

**Comment by jkraemer** [comment]
good point
