### ISSUE TITLE
Concatenate method throwing error 'undefined method to_str for Hash'

### ISSUE THREAD

**Issue by johnnybuma** [jkraemer/pdf-forms#56]
NoMethodError - undefined method `to_str' for #<Hash:0x007fc1b1680900>:
  pdf-forms (1.0.0) lib/pdf_forms/normalize_path.rb:9:in`normalize_path'
  pdf-forms (1.0.0) lib/pdf_forms/pdftk_wrapper.rb:92:in `block in cat'
  pdf-forms (1.0.0) lib/pdf_forms/pdftk_wrapper.rb:92:in`cat'

I am trying to use this method to remove pages not combine files like this

@pdftk.cat( {file_input_path => ['1-2', '10-11']}, file_output_path)

I also duplicated your test script for this method and am getting the same error when trying to combine files.

The method works fine for simply combining 2 files like this

@pdftk.cat file_input_path_1, file_input_path_2, file_output_path

The error only arises when passing a Hash with page ranges as an argument

**Comment by johnnybuma** [comment]
I was able to achieve my desired result by bypassing the cat method and opting for call_pdftk instead like such

    @pdftk.call_pdftk file_input_path, 'cat', ['1-2', '10-11'], 'output' , file_output_path

**Comment by jkraemer** [comment]
I'll consider adding better support for this in a later version

**Comment by jkraemer** [comment]
Actually this is implemented already :)
