### ISSUE TITLE
fill_form hangs for minutes until interrupted

### ISSUE THREAD

**Issue by stevehanson** [jkraemer/pdf-forms#58]
When I try to fill a form, it just hangs for minutes until I interrupt it. I am using [this form](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf), which is just a random form I found online. And here's my code:

```ruby
pdftk = PdfForms.new('/usr/local/bin/pdftk')

pdftk.get_field_names '/tmp/example.pdf'
=> ["Given Name Text Box", "Family Name Text Box", ...]

pdftk.fill_form '/tmp/example.pdf', '/tmp/filled.pdf', 'Given Name Text Box' => "Steve", 'Family Name Text Box' => "Hanson"
# just hangs for minutes
```

If I interrupt, I get:

```
from /~/dev/my-app/vendor/bundle/gems/safe_shell-1.0.3/lib/safe_shell.rb:12:in `read'
```

It was also hanging on `get_field_names` for another form I was trying to use. Am I just doing something wrong? Would appreciate any advice.

I'm on Mac OS X El Capitan and installed pdftk using `brew install https://raw.github.com/quantiverge/homebrew-binary/pdftk/pdftk.rb`

**Comment by dikond** [comment]
I have similar issue, it hangs on `get_field_names` until interrupt signal.
macOS Sierra, installed pdftk via `brew install pdftk`

**Comment by deepak07** [comment]
I am also facing similar issue. I am using `MacOS Sierra` and pdftk `2.02 `.

**Comment by jkraemer** [comment]
If a simple `pdftk /path/to/pdf dump_data_fields` on the command line is hanging as well there's nothing I can do. Please file a bug with pdftk in that case.

**Comment by dikond** [comment]
Guys, I found the problem. Basically, it is the same issue as [this one from SO](http://stackoverflow.com/questions/32505951/pdftk-server-on-os-x-10-11). You probably have El Capitan of Sierra as OS, and the package you've installed from official site is outdated. Use the link that Sid posted - this package fixed an issue for me.

**Comment by deepak07** [comment]
@dikond Thanks for link. I was banging my head over my desk literally.  
@jkraemer The issue is with the pdfkt installation. Not with the gem. Thanks for pointing it out.

**Comment by stevehanson** [comment]
@dikond thanks for sharing. Installing the updated pdftk version that Sid shared on that SO thread did fix it for me!

Sorry for posting the issue here instead of with pdftk, which is where the problem was. Seems like we can close this now.

**Comment by jkraemer** [comment]
thanks for reporting back your success.
