### ISSUE TITLE
Corrupt PDF after flatten

### ISSUE THREAD

**Issue by tdgvrr** [jkraemer/pdf-forms#60]
I have a PDF containing form elements that I've processed using this command: 

`pdftk input.pdf output output.pdf flatten`

It seems to work properly, but I can't read the resulting output PDF in Adobe Acrobat on MacOS X (Acrobat version is 15.20.20042.205528). When opening the file, Acrobat complains 

> "An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem.".

The PDF displays somewhat properly, except that form fields that were updated in the original PDF seem to be missing. 

The output PDF does display correctly in the OS X "Preview" app. 

Is there perhaps something else I need to do to "flatten" the PDF?

**Comment by jkraemer** [comment]
sorry I have no idea. This appears to be more of a pdftk problem, did you try contacting the guys over at pdflabs.com?
