### ISSUE TITLE
Another tool for PDF?

### ISSUE THREAD

**Issue by tonatiuh** [jkraemer/pdf-forms#61]
Are there any plans to make this gem compatible with another PDF tool? It seems PDFtk is not available in Linux distros like Fedora.

**Comment by jkraemer** [comment]
Do you have any suggestion what such a tool might be? I'm not aware of any.

Regarding Fedora / other Linux distributions - did you try building from source / rolling your own packages? https://www.pdflabs.com/docs/install-pdftk-on-redhat-or-centos/ might be of help.

**Comment by tonatiuh** [comment]
Thanks. The instructions in such link didn't work for me because a required library is not in Fedora.

This did work: 

```
wget http://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64/pdftk-2.02-5.10.x86_64.rpm  http://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64/libgcj-gcc6-6.3.1+r245113-1.5.x86_64.rpm`
sudo dnf install *rpm
```
