### ISSUE TITLE
pdftk not supported on more and more platforms

### ISSUE THREAD

**Issue by wkhatch** [jkraemer/pdf-forms#63]
Is anything being done to deal with the fact that pdftk is not well supported? For instance, it's not supported on aws linux without a lot of additional hassle. It seems that the library is not well maintained at this point

**Comment by dimitrovmaksim** [comment]
Sorry if it's not appropriate to post this here, and i know this issue has been opened long ago. But we had the issue with installing pdftk on AWS EB server and in the end we could assemble а working solution: [Click](https://hone.eu/blog/install-pdftk-on-an-aws-elasticbeanstalk-environment). If it's not appropriate to post this link here, please feel free to delete the comment. Hope it helps.

**Comment by wkhatch** [comment]
Thanks Dimitri; I'll check that out.

**Comment by jkraemer** [comment]
On current Debian stable (Stretch) it's still just a simple `apt install pdftk` therefore I don't think there are technical issues preventing it from being supported on other platforms.
