### ISSUE TITLE
Cant get Hebrew to fill Correctly

### ISSUE THREAD

**Issue by DrakenZA** [jkraemer/pdf-forms#64]
Ive been looking through the issues here, and ive seen a lot of people complain about this, but it gets closed and not resolved.

Im literally trying to input Hebrew text into a PDF form, that has the exact same line of text as the one im trying to 'fill' in. So the PDF MUST have the font and characters, because its literally displaying it.

Nothing i can do from any of the the suggestions has been able to get non english to fill, even when you are trying to fill in a word that is present in the PDF, hence it has the needed embedded files.

Checked the dump_data_fields_utf8 on the PDF, and its fine.

If i add 'need_appearances' to the end of the command line, i end up with a pdf file that has blank forms, but if i click on one of the forms, i see the hebrew text. If i then simply add any character to the end of the string(via a external pdf editor), all of sudden functions.

This seems to have nothing to do with fonts, because once you do the trick ^ above, they even have the correct fonts.

**Comment by jkraemer** [comment]
Is it possible to let me have a look at the PDF form in question? Attach it here or send it by email to jk@jkraemer.net.

**Comment by DrakenZA** [comment]
[test.pdf](https://github.com/jkraemer/pdf-forms/files/1126535/test.pdf)

just a basic pdf created in phantomPDF.

Im starting to think the only thing that might work is adobe.

**Comment by jkraemer** [comment]
That PDF doesn't display correctly here (nonsense characters in Chrome, blank page in my PDF viewer (evince on Debian). I actually have zero experience with forms that were not created with Adobe Acrobat, but it might well be possible that these are the only ones that work reliably.

**Comment by jkraemer** [comment]
Having that said, I just merged #59  that implements embedding UTF16 in FDF files, maybe give that a try?

**Comment by DrakenZA** [comment]
UTF16 doesnt seem to help. Soon in the future ill try with a pdf created with adobe rather.

**Comment by jkraemer** [comment]
closing due to no more feedback
