### ISSUE TITLE
Uninitialized Constant PdfForms::PdftkWrapper::InvalidArgumentError

### ISSUE THREAD

**Issue by engineersmnky** [jkraemer/pdf-forms#66]
Not a huge issue but you forgot to define `InvalidArgumentError` unless you just meant `ArgumentError`. 

This causes an unhandled `NameError` in `PdfForms::PdftkWrapper#normalize_args`.

**Comment by theasteve** [comment]
@engineersmnky I'm currently getting that error ```uninitialized constant PdfForms::PdftkWrapper::InvalidArgumentError``` In a Rails application having the following `PDFTK_PATH=/vendor/pdftk/bin/pdftk` on PATH

**Comment by jkraemer** [comment]
that's fixed now
