### ISSUE TITLE
Attach digital signature file or image in pdf

### ISSUE THREAD

**Issue by balajisivsubramanip** [jkraemer/pdf-forms#67]
How to attach a digital signature or image in pdf.
Is there any way to do within 'pdf-forms' gem

**Comment by rylanb** [comment]
I also am interested in this question. My initial research says no, but would love a solution where you can specify an image to be inserted into a PDF transparent button or some such thing!

**Comment by rylanb** [comment]
Also: https://github.com/jkraemer/pdf-forms/issues/24 has a discussion around this @balajisivsubramanip

**Comment by jkraemer** [comment]
As far as I am aware there is no way to do this through the PDF forms mechanism.
