### ISSUE TITLE
Missing Options (drop_xfa)

### ISSUE THREAD

**Issue by alwesam** [jkraemer/pdf-forms#68]
I used the pdf-forms gem to populate a PDF file, which apparently had XFA data.  The output file is not showing filled in form fields when I open it with Adobe Reader (no problem when a PDF viewer such as xpdf).  The problem goes away when I add "drop_xfa" to the pdftk command, but AFAIK the gem doesn't support appending any options aside from flatten.

I made a small change in one of the source files (lib/pdf_forms/pdftk_wrapper.rb) where I enabled appending the "drop_xfa" option on my local branch and it's working.

Please advise.  I can make a pull request with my changes.  It seems that there are other missing options so they can be included too.

Thanks

**Comment by jkraemer** [comment]
You can now use `drop_xfa: true` and `drop_xmp: true` options.
