### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by yv3s** [jkraemer/pdf-forms#72]
Hi,

I don't know what is wrong with my setup but I cannot read any pdf file apparently ! 
I initiate without any problem `pdftk = PdfForms.new('/usr/local/bin/pdftk')` but then I cannot get the pdf fields, either with a local pdf or one hosted on the web, I keep getting an IOError.

My controller :
` def dossier_cpf
          @pdftk = PdfForms.new(Cliver.detect('pdftk'))
          @fields = @pdftk.get_field_names "#{Rails.root}/assets/images/dossier_cpf.pdf"
end`

Thanks for your help

**Comment by abygeorge** [comment]
how did you solve this?
