### ISSUE TITLE
Support for pdftk-java 

### ISSUE THREAD

**Issue by nathanhruby** [jkraemer/pdf-forms#75]
Hi,

Debian was (as far as I can tell) the last distro to support libgcj and pdftk.  As of Buster they are no longer supporting it
- https://packages.debian.org/buster/pdftk
Instead they are replacing it with a port of pdftk to java:
- https://gitlab.com/pdftk-java/pdftk

Does pdf-forms work with or support pdftk-java?

**Comment by jkraemer** [comment]
I never looked into this, but it seems that a simple wrapper script around the `java -jar pdftk-all.jar` call (passing on any command line options) which would then be set as the `pdftk` executable in pdf-forms (`PdfForms.new('/path/to/script')`) might work.

Please report back if you give this a try, so we can add it to the README.

**Comment by pavel-jurasek-hypofriend-de** [comment]
Hi,
it's working just deployed to our platform. java-pdftk works.

Wrapper script:

```
#!/bin/sh
MYSELF=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
    java="$JAVA_HOME/bin/java"
fi
exec "$java" $java_args -jar $MYSELF "$@"
exit 1
```

how to create wrapper:

```bash
cat /bin/stub.sh /pdftk/build/libs/pdftk-all.jar > pdftk.run && chmod +x pdftk.run
```

**Comment by jkraemer** [comment]
thank you! I added this info to the README.

**Comment by tfmertz** [comment]
Hmm, we were able to get it working without a java wrapper script just by installing the `pdftk-java` package and passing through that executable to pdf-forms gem. Maybe we just go lucky and our distro had that package? Or the docs are a bit out of date.

Running on ruby:2.6.6 container (Debian Buster)
```
apt-get update && apt-get install -y pdftk-java
which pdftk
# returns something like /usr/bin/pdftk
```

In rails code
```
pdftk = PdfForms.new('/usr/bin/pdftk')
```

Hope that's helpful, if it's wrong I welcome any corrections or insights :)

**Comment by pavel-jurasek-hypofriend-de** [comment]
> Hmm, we were able to get it working without a java wrapper script just by installing the `pdftk-java` package and passing through that executable to pdf-forms gem. Maybe we just go lucky and our distro had that package? Or the docs are a bit out of date.
> 
> Running on ruby:2.6.6 container (Debian Buster)
> 
> ```
> apt-get update && apt-get install -y pdftk-java
> which pdftk
> # returns something like /usr/bin/pdftk
> ```
> 
> In rails code
> 
> ```
> pdftk = PdfForms.new('/usr/bin/pdftk')
> ```
> 
> Hope that's helpful, if it's wrong I welcome any corrections or insights :)

Hi, indeed on Debian base operation system it would work, but our platform running on Alpine where pdftk-java is not available..

**Comment by mikeappell** [comment]
Not sure if this is helpful, but this works for us to install (what I believe to be) the current latest version of pdftk-java in a Docker container and use it with pdf-forms:

```Dockerfile
RUN wget -O /usr/bin/pdftk "https://gitlab.com/pdftk-java/pdftk/-/jobs/1527259632/artifacts/raw/build/native-image/pdftk" \
    && chmod a+x /usr/bin/pdftk
```
and then
```Ruby
PdfForms.new('/usr/bin/pdftk')
```
