### ISSUE TITLE
Non-Zero exit status of pdftk is ignored

### ISSUE THREAD

**Issue by sriedel** [jkraemer/pdf-forms#80]
Archlinux supplies the java port of pdftk as the 'pdftk' package, but apparently has not all required depencies declared. 
Calling PdfForms#get_fields returns an empty hash in this case.

The cause is that #pdftk.call_pdftk path, dump_method in lib/pdf_forms/pdf.rb:35 returns the following string:

"Error: could not load a required library for this operation.\njava.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils\nMake sure that bcprov and commons-lang3 are installed and included in the\nclasspath. See also https://gitlab.com/pdftk-java/pdftk/issues/2.\n   No output created.\n"

and the underlying process terminates with exit status 1.

Maybe a solution would be to use SafeShell.execute! instead of SafeShell.execute in PdftkWrapper#call_pdftk

**Comment by rafalpetryka** [comment]
Based on history of 1.4.0
https://github.com/jkraemer/pdf-forms/blob/master/History.txt
i think that issue could be closed

**Comment by jkraemer** [comment]
true :)
