### ISSUE TITLE
Could the SafeShell dependency be dropped?

### ISSUE THREAD

**Issue by stevecrozz** [jkraemer/pdf-forms#83]
Seems like this dependency could be dropped and replaced with standard library calls. Doesn't seem like SafeShell is adding anything. Should we do it?

```ruby
    # Returns string output (combined stdout and stderr) and Process::Status object
    def call_pdftk(*args)
      Open3.popen2e(pdftk, *args.flatten)
    end
```

**Comment by jkraemer** [comment]
if at all, `capture2e` would be the way to go as we sometimes need the output. However Open3, for whatever reason, does not set `$?` which would break the documented behavior of the method.
